document.addEventListener('DOMContentLoaded', () => {
    // === Tab Switching Logic ===
    const tabBtns = document.querySelectorAll('.tab-btn');
    const tabContents = document.querySelectorAll('.tab-content');

    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            // Remove active class from all
            tabBtns.forEach(b => b.classList.remove('active'));
            tabContents.forEach(c => c.classList.remove('active'));

            // Add active class to clicked
            btn.classList.add('active');
            const targetId = btn.getAttribute('data-tab');
            document.getElementById(targetId).classList.add('active');
        });
    });

    // === State Management (localStorage) ===
    let apis = JSON.parse(localStorage.getItem('merchkuQ_apis')) || [];
    let chatMessages = JSON.parse(localStorage.getItem('merchkuQ_chat')) || [];
    // Store virtual files generated by AI
    let projectFiles = JSON.parse(localStorage.getItem('merchkuQ_files')) || [];

    // Initialize UI
    renderApiList();
    renderChatHistory();

    // === API Management ===
    const apiNameInput = document.getElementById('api-name-input');
    const apiUrlInput = document.getElementById('api-url-input');
    const addApiBtn = document.getElementById('add-api-btn');
    const apiList = document.getElementById('api-list');

    addApiBtn.addEventListener('click', () => {
        const name = apiNameInput.value.trim();
        const url = apiUrlInput.value.trim();

        if (name && url) {
            apis.push({ name, url });
            saveApis();
            renderApiList();
            apiNameInput.value = '';
            apiUrlInput.value = '';
        } else {
            alert('Proszę podać nazwę i URL/Klucz API.');
        }
    });

    function renderApiList() {
        if (!apiList) return;
        apiList.innerHTML = '';
        apis.forEach((api, index) => {
            const div = document.createElement('div');
            div.className = 'api-item';
            div.innerHTML = `
                <span><strong>${api.name}</strong></span>
                <button onclick="removeApi(${index})">X</button>
            `;
            apiList.appendChild(div);
        });
    }

    window.removeApi = function(index) {
        apis.splice(index, 1);
        saveApis();
        renderApiList();
    };

    function saveApis() {
        localStorage.setItem('merchkuQ_apis', JSON.stringify(apis));
    }

    // === AI Chat & Godot Generation ===
    const chatHistory = document.getElementById('chat-history');
    const aiPromptInput = document.getElementById('ai-prompt-input');
    const sendPromptBtn = document.getElementById('send-prompt-btn');
    const uploadBtn = document.getElementById('upload-btn');
    const fileUploadInput = document.getElementById('file-upload-input');

    // Handle file uploads
    if (uploadBtn && fileUploadInput) {
        uploadBtn.addEventListener('click', () => {
            fileUploadInput.click();
        });

        fileUploadInput.addEventListener('change', (e) => {
            const file = e.target.files[0];
            if (!file) return;

            const reader = new FileReader();
            reader.onload = (event) => {
                const dataUrl = event.target.result;
                const fileName = file.name;

                // Add to virtual files
                addVirtualFile(fileName, dataUrl, true);

                // Add message to chat
                addChatMessage('user', `[Przesłano plik: ${fileName}]`);
                addChatMessage('system', `AI: Plik ${fileName} został pomyślnie wgrany do projektu! Otrzymałem dostęp do niego i będę mógł go wykorzystać.`);
            };

            // Read as data URL to easily store in localStorage
            reader.readAsDataURL(file);

            // Reset input so the same file can be uploaded again if needed
            fileUploadInput.value = '';
        });
    }

    sendPromptBtn.addEventListener('click', handleSendPrompt);
    aiPromptInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSendPrompt();
        }
    });

    function handleSendPrompt() {
        const text = aiPromptInput.value.trim();
        if (!text) return;

        addChatMessage('user', text);
        aiPromptInput.value = '';

        const lowerText = text.toLowerCase();

        // Check configured APIs
        if (apis.length === 0) {
            setTimeout(() => {
                addChatMessage('system', `System: Brak połączonych API. Przejdź do zakładki "API", aby dodać klucze i odblokować możliwości AI.`);
            }, 500);
            return;
        }

        if (apis.length === 1) {
            // Single API logic
            setTimeout(() => {
                let aiResponse = `Zrozumiałem polecenie: "${text}". Przekazuję instrukcje do wbudowanego silnika Godot.`;

                if (lowerText.includes('skrypt')) {
                    aiResponse += `\nWygenerowano nowy skrypt (np. Player.gd) i dodano do projektu!`;
                    addVirtualFile('Player.gd', `extends CharacterBody2D\n\nconst SPEED = 300.0\n\nfunc _physics_process(delta):\n\tpass # Skrypt wygenerowany przez AI`);
                }
                if (lowerText.includes('model') || lowerText.includes('3d')) {
                    aiResponse += `\nStworzono bazowy model 3D (PlayerModel.obj) i dodano do sceny.`;
                    addVirtualFile('PlayerModel.obj', `# Prosty model OBJ wygenerowany przez AI\nv 0.0 0.0 0.0`);
                }

                addChatMessage('system', `AI (${apis[0].name}): ${aiResponse}`);
            }, 1200);
        } else {
            // Multi API logic - divide roles
            setTimeout(() => {
                addChatMessage('system', `System: Wykryto ${apis.length} API. Rozpoczynam dzielenie zadań na role...`);

                // Simulate Programmer API response
                setTimeout(() => {
                    const programmerApiName = apis[0].name;
                    let progResponse = `Analizuję mechanikę. `;
                    if (lowerText.includes('skrypt') || lowerText.includes('poruszan')) {
                        progResponse += `Tworzę skrypt kontrolera postaci (Player.gd).`;
                        addVirtualFile('Player.gd', `extends CharacterBody2D\n\nconst SPEED = 300.0\n\nfunc _physics_process(delta):\n\tpass # Skrypt wygenerowany przez ${programmerApiName} (Programista)`);
                    } else {
                        progResponse += `Konfiguruję podstawowe parametry sceny głównej.`;
                    }
                    addChatMessage('system-programmer', `[Role: Programista] ${programmerApiName}: ${progResponse}`);
                }, 1000);

                // Simulate Graphic Designer API response
                setTimeout(() => {
                    const graphicApiName = apis[1].name;
                    let graphResponse = `Przygotowuję zasoby wizualne. `;
                    if (lowerText.includes('model') || lowerText.includes('3d') || lowerText.includes('grafik')) {
                        graphResponse += `Tworzę i ładuję model 3D (PlayerModel.obj).`;
                        addVirtualFile('PlayerModel.obj', `# Prosty model OBJ wygenerowany przez ${graphicApiName} (Grafik)\nv 0.0 0.0 0.0`);
                    } else {
                        graphResponse += `Ustalam oświetlenie i środowisko wizualne.`;
                    }
                    addChatMessage('system-graphic', `[Role: Grafik] ${graphicApiName}: ${graphResponse}`);
                }, 2000);

            }, 800);
        }
    }

    function addVirtualFile(filename, content, isBase64 = false) {
        // Prevent duplicates in a simple way
        const existing = projectFiles.findIndex(f => f.filename === filename);
        if (existing !== -1) {
            projectFiles[existing].content = content;
            projectFiles[existing].isBase64 = isBase64;
        } else {
            projectFiles.push({ filename, content, isBase64 });
        }
        localStorage.setItem('merchkuQ_files', JSON.stringify(projectFiles));
    }

    function addChatMessage(role, text) {
        chatMessages.push({ role, text });
        saveChat();
        appendMessageToUI(role, text);
    }

    function renderChatHistory() {
        if(!chatHistory) return;
        const children = Array.from(chatHistory.children);
        for (let i = 1; i < children.length; i++) {
            chatHistory.removeChild(children[i]);
        }
        chatMessages.forEach(msg => {
            appendMessageToUI(msg.role, msg.text);
        });
    }

    function appendMessageToUI(role, text) {
        const div = document.createElement('div');
        div.className = `message ${role}`;
        div.innerText = text;
        chatHistory.appendChild(div);
        chatHistory.scrollTop = chatHistory.scrollHeight;
    }

    function saveChat() {
        localStorage.setItem('merchkuQ_chat', JSON.stringify(chatMessages));
    }

    // === Game Emulator ===
    const startEmulatorBtn = document.getElementById('start-emulator-btn');
    const playOverlay = document.getElementById('play-overlay');
    const emulatorScreen = document.getElementById('emulator-screen');
    const emulatorStatus = document.getElementById('emulator-status');

    if(startEmulatorBtn) {
        startEmulatorBtn.addEventListener('click', () => {
            playOverlay.style.display = 'none';
            emulatorScreen.style.display = 'flex';

            setTimeout(() => {
                emulatorStatus.innerHTML = '<span style="color: white;">GRA URUCHOMIONA (Wczytano wygenerowane zasoby)</span>';
            }, 1500);
        });
    }

    // === Download Game ===
    const downloadGameBtn = document.getElementById('download-game-btn');

    if(downloadGameBtn) {
        downloadGameBtn.addEventListener('click', () => {
            if (typeof JSZip === 'undefined') {
                alert('Biblioteka JSZip nie została załadowana.');
                return;
            }

            const zip = new JSZip();

            // Base project files
            zip.file("project.godot", `
config_version=5

[application]
config/name="merchkuQ_Project_AI"
run/main_scene="res://main.tscn"
            `.trim());

            zip.file("main.tscn", `[gd_scene format=3 uid="uid://test"]\n[node name="Main" type="Node2D"]`);

            // Add virtual files generated by AI and uploaded files
            projectFiles.forEach(file => {
                if (file.isBase64) {
                    // Extract the base64 part of the data URL (remove "data:image/png;base64,")
                    const base64Data = file.content.split(',')[1];
                    zip.file(file.filename, base64Data, {base64: true});
                } else {
                    zip.file(file.filename, file.content);
                }
            });

            // Generate and download
            zip.generateAsync({type:"blob"}).then(function(content) {
                saveAs(content, "merchkuQ_GameProject.zip");
            });
        });
    }

    // === Settings ===
    const clearDataBtn = document.getElementById('clear-data-btn');
    if (clearDataBtn) {
        clearDataBtn.addEventListener('click', () => {
            if(confirm("Czy na pewno chcesz wyczyścić wszystkie dane (API, chat, pliki gry)?")) {
                localStorage.clear();
                window.location.reload();
            }
        });
    }
});
